namespace: sofia-mosquera-dev
name: mi-app-third

replicaCount: 1


metadata:
  labels:
    app: mi-app-third

container:
  image: sofiamosquera/second_mc
  tag: build-7
  port: 3000
  resources:
    requests:
      cpu: "200m"
      memory: "300Mi"
    limits:
      cpu: "4000m"
      memory: "500Mi"
hpa:
  minReplicas: 1
  maxReplicas: 5

configmap:
  database: "192.168.1.1"

secret:
  # plain text password; template will base64-encode when placing into `data:`
  password: "hola"

