apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment-third-{{ .Values.metadata.labels.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.metadata.labels.app }}
    areanegocio: tecnologia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
    spec:
      containers:
        - name: contenedor-principal
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}  # <-- Reemplaza con la imagen que quieras usar
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.container.port }}
          resources:
            requests:
              cpu: {{ .Values.container.resources.requests.cpu }}
              memory: {{ .Values.container.resources.requests.memory }}
            limits:
              cpu: {{ .Values.container.resources.limits.cpu }}
              memory: {{ .Values.container.resources.limits.memory }}
          startupProbe:
            httpGet:
              path: /startup
              port: {{ .Values.container.port }}
            failureThreshold: 5
            periodSeconds: 10
